services:
  mongodb:
   image: mongo:7.0-jammy

   restart: always
   
   container_name: mongodb
   ports:
    - "27007:27017"
   volumes:
    - ./mongodb:/data/db 
   networks:
    - backend



networks:
  backend: